development:
  sessions:
    default:
      database: mongo_forms_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  sessions:
    default:
      database: mongo_forms_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      database: mongo_forms_production
      hosts:
        - localhost:27017
      options:
        read: primary
  options:
